<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Play</title>
    <?= $this->headScript()
    	->prependFile('/js/main.js')
        ->prependFile('/extjs/locale/ext-lang-nl.js')
        ->prependFile('/extjs/ext-all-debug.js')

    ; ?>
    <?= $this->headLink()
        ->prependStylesheet('/extjs/resources/css/ext-all.css')
        ->prependStylesheet('/css/main.css')
    ; ?>
</head>
<body>
<?php echo $this->layout()->content ?>
</body>
</html>
